name = "Newb X Legacy"
version = [0, 15, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
ยงc%w
ยง7- An enchanced vanilla shader for Minecraft!
%v
ยง3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Weather", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Box Clouds
'''

[[subpack]]
define = "CHUNK_ANIM"
materials = ["RenderChunk"]
description = '''
Chunk loading animation
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
